image: rust:latest

stages:
  - build
  - deploy

rust-latest:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

pages:
  stage: deploy
  script:
  - cargo doc
  - mkdir public
  - mv targer/doc public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
