stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

pages:
  stage: deploy
  script:
  - cargo doc
    # Remove libc from documentation to speed up deploy
  - rm -r target/doc/libc
  - rm -r target/doc/src/libc
  - mkdir public
  - mv targer/doc public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
